/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as BookingShowtimeIdRouteImport } from './routes/booking.$showtimeId'

const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingShowtimeIdRoute = BookingShowtimeIdRouteImport.update({
  id: '/booking/$showtimeId',
  path: '/booking/$showtimeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bookings' | '/booking/$showtimeId' | '/movies/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookings' | '/booking/$showtimeId' | '/movies/$movieId'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/booking/$showtimeId'
    | '/movies/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  BookingShowtimeIdRoute: typeof BookingShowtimeIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$showtimeId': {
      id: '/booking/$showtimeId'
      path: '/booking/$showtimeId'
      fullPath: '/booking/$showtimeId'
      preLoaderRoute: typeof BookingShowtimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  BookingShowtimeIdRoute: BookingShowtimeIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
